### ISSUE TITLE
Error in assignID, autoplace-control with name 'enemy-base' does not exist

### ISSUE THREAD

**Issue by bigyihsuan** [Nexela/autofill#10]
![](http://i.imgur.com/4EPYaQL.png)

Factorio 0.14.5, Autofill 1.4.5.

**Comment by Nexela** [comment]
Do you have any other mods installed?  Autofill doesn't do anything with autoplace controls or enemy-base

**Comment by bigyihsuan** [comment]
Here ya go: ~[](http://i.imgur.com/CPlOsSq.png)

I've tried the "remove half the mods then test" method a few times already; it's only occurring when all of the mods are installed.

**Comment by Nexela** [comment]
You have a lot of mods which duplicate functionality and change the same things. It might possibly be an error with RSO and one or all of the peace/artifact mods. As it stands now there isn't enough for me to go on.  If you still have your factorio current log you can attach here and I will take a quick peek but it probably won't tell me much.
