### ISSUE TITLE
Doesn't work on Additional Turrets mod 0.14.20 (1.4.5)

### ISSUE THREAD

**Issue by buzzorth** [Nexela/autofill#11]
Autofill doesn't work when placing or using the default control + f to add ammo to Bob's Cannon and Rocket turrets. Works fine on Bob's Sniper turret, so it might be because of the different ammo the other turrets use.

To make sure it wasn't a bug in my settings i tried re-downloading Autofill and also tried using the command (/c remote.call("af", "resetMod")). But that didn't do anything.

**Comment by Nexela** [comment]
Unless something has changed, Bobsmods doesn't have Cannon or Rocket turrets. These are possibly added through another mod, If you know the name of that mod I will look into adding compatibility for it or posting the command for you to add them to your personal set.

**Comment by buzzorth** [comment]
Arh, sorry. It said bob's warfare when I moused over it in-game but it's the additional turrets mod. I see from the forum that someone already requested it be added. :)

Thanks for the fast respons and thanks for working on the mod. ;)

**Comment by Nexela** [comment]
Thanks for the update, I would have responded sooner but I am not getting followup notifications for some reason :)


I will try and get a update out this weekend to add in support for this mod since a few people have asked.
