### ISSUE TITLE
Support for Uranium_rounds_magazine

### ISSUE THREAD

**Issue by Taszi** [Nexela/autofill#16]
Is not fill [Uranium_rounds_magazine](Uranium_rounds_magazine) into the turrets. Someone know how to change or fix it?

**Comment by Nexela** [comment]
I will add them this weekend, Thank you!

**Comment by sparr** [comment]
@Nexela I'd like to augment the mod to automatically detect and sort new types of ammo. That would include automatic support for uranium_rounds_magazine, additional mods, future versions of the base game with new ammo types, etc.

If you're in favor of that feature, reply here, and I'll submit a PR when I've got it working.

**Comment by Nexela** [comment]
Take a peek at the 2.0 branch of autofill. Most of that stuff is implemented. If you are not far off from it though I will gladly take a peek at it.

**Comment by Taszi** [comment]
Realy nice job. Thank you!
