### ISSUE TITLE
Factorio 0.16.6 zipped version, added to an existing bobs game, error line 51: pdata is nil

### ISSUE THREAD

**Issue by DaveInTexas** [Nexela/autofill#25]
![new bitmap image](https://user-images.githubusercontent.com/8439723/34190854-c09106da-e508-11e7-8f00-7a51d0fee3ea.jpg)

Bobs plus a few QOL (Picker extended, Even Distro, etc)
modlist: [mod-list.zip](https://github.com/Nexela/autofill/files/1574128/mod-list.zip)

**Comment by Nexela** [comment]
On my todo list just really busy at work

**Comment by CzBuCHi** [comment]
same issue but without Bob...

my mods:
- Base mod
- Bottleneck
- Long Reach
- Nanobots: Easrly Bots
- Resource Spanw Overhaul

**Comment by beugnen** [comment]
@Nexela  hmm.....2 years later and still not fixed?  Saying you are busy is kinda bad customer service

**Comment by Nexela** [comment]
What do you want me to say? I write/fix these IN MY SPARE TIME. without earning any MONEY..... to pay for things like MORTGAGES and FOOD and BILLS. You are not a customer you are an ungrateful freeloader.   

Want to get this fixed faster,  give me a good reason.
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=nexela%40gmail.com&item_name=Make+Mods+Great+Again&currency_code=USD&source=url

**Comment by TheStaplergun** [comment]
Lmao, @mickyd is a fucking clown. Super entitled. Pays nothing and expects something in return. Hahaha.

**Comment by mickyd** [comment]
@Nexela Give you money?  Sure.  You can use it to learn how to program

**Comment by TheStaplergun** [comment]
https://github.com/tauntingfrenchguard You could also just create a PR and fix it yourself, if you're such a god at coding.

**Comment by beugnen** [comment]
It must be frustrating for you that the only time you get any form of recognition is doing open source work?  Guess you’re pretty mediocre at work?

Time for a career change me thinks.

**Comment by TheStaplergun** [comment]
Lmao. Troll account.
