### ISSUE TITLE
Error: Autofill 1.4.1 in Factorio 0.13.4

### ISSUE THREAD

**Issue by Pkkid50002002** [Nexela/autofill#6]
factorio
8/5/2016 , 9:42:53 AM
Factorio 0.13.4

![error autofill ver 1 4 1](https://cloud.githubusercontent.com/assets/20860496/17438839/e44c30a0-5af2-11e6-9899-e276db348ced.jpg)

Will not work in game.

**Comment by Nexela** [comment]
> Factorio 0.13.4

Is there a specific reason you are still on this version?  You should consider updating to the latest experimental version as a lot of bugs have been fixed and some API calls have been added or changed.

And well I am not sure if am or will be using them at this time I don't want to forget this critical step when I do.  For now you can manually adjust the dependency in the info.json file and it might work on older versions.

**Comment by Pkkid50002002** [comment]
Thanks

**Comment by Pkkid50002002** [comment]
That fixed it. Who knew. :)
